export const CARDS = {
    c0: "Gideon's Valor",
    c1: "Stormbreaker",
    c2: "Knight's Rally",
    c3: "Gideon's Shieldwall",
    c4: "Thunderstrike",
    c5: "Celestial Blessing",
    c6: "Stormforged Armor",
    c7: "Paladin's Oath",
    c8: "Lightning Charge",
    c9: "Tempest Blessing",
    c10: "Divine Intervention",
    c11: "Thunderous Charge",
    c12: "Resolute Defender",
    c13: "Wrath of the Storm",
    c14: "Beacon of Light",
    c15: "Ironclad Defense",
    c16: "Hammer of Justice",
    c17: "Ironheart's Call",
    c18: "Valiant Charge",
    c19: "Guardian's Shield",
    c20: "Divine Retribution",
    c21: "Iron Will",
    c22: "Celestial Blessing",
    c23: "Judgment Day",
    c24: "Steel Tempest",
    c25: "Aegis of the Ancients",
    c26: "Sacred Ground",
    c27: "Warrior's Resolve",
    c28: "Phoenix Rebirth",
    c29: "Eternal Vigilance",
}