export const CARDS = {
    c1: "Gideon's Valor",
    c2: "Stormbreaker",
    c3: "Knight's Rally",
    c4: "Gideon's Shieldwall",
    c5: "Thunderstrike",
    c6: "Celestial Blessing",
    c7: "Stormforged Armor",
    c8: "Paladin's Oath",
    c9: "Lightning Charge",
    c10: "Tempest Blessing",
    c11: "Divine Intervention",
    c12: "Thunderous Charge",
    c13: "Resolute Defender",
    c14: "Wrath of the Storm",
    c15: "Beacon of Light",
    c16: "Ironclad Defense",
    c17: "Hammer of Justice",
    c18: "Ironheart's Call",
    c19: "Valiant Charge",
    c20: "Guardian's Shield",
    c21: "Divine Retribution",
    c22: "Iron Will",
    c23: "Celestial Blessing",
    c24: "Judgment Day",
    c25: "Steel Tempest",
    c26: "Aegis of the Ancients",
    c27: "Sacred Ground",
    c28: "Warrior's Resolve",
    c29: "Phoenix Rebirth",
    c30: "Eternal Vigilance",
}