
export const CARDS2 = [
    "Gideon's Valor",
    "Stormbreaker",
    "Knight's Rally",
    "Gideon's Shieldwall",
    "Thunderstrike",
    "Celestial Blessing",
    "Stormforged Armor",
    "Paladin's Oath",
    "Lightning Charge",
    "Tempest Blessing",
    "Divine Intervention",
    "Thunderous Charge",
    "Resolute Defender",
    "Wrath of the Storm",
    "Beacon of Light",
    "Ironclad Defense",
    "Hammer of Justice",
    "Ironheart's Call",
    "Valiant Charge",
    "Guardian's Shield",
    "Divine Retribution",
    "Iron Will",
    "Celestial Blessing",
    "Judgment Day",
    "Steel Tempest",
    "Aegis of the Ancients",
    "Sacred Ground",
    "Warrior's Resolve",
    "Phoenix Rebirth",
    "Eternal Vigilance",
]